### ISSUE TITLE
Handle unknown attributes in response body

### ISSUE THREAD

**Issue by voke** [mbirman/billogram#2]
Maybe it would be nice to check for `respond_to?(attr_name=)` in `Resource#initialize` to avoid breaking the gem as soon as they make changes to the API.

**Comment by mbirman** [comment]
@voke good idea. We had this piece of code before and I removed it, because without it we can early notice if API response is changed or something is broken. Still not sure what is the best option.

**Comment by voke** [comment]
Maybe there should be a config option like `strict=true` or use `warn()` when a some attributes can't be parsed correctly.

**Comment by mbirman** [comment]
Yeah, this sounds great

**Comment by mbirman** [comment]
@voke we will warn about any unknown attribute. Thank you once again :)
